name: ci
on:
  push: { branches: [main, dev] }
  pull_request: { branches: [main, dev] }
  workflow_dispatch:

permissions:
  contents: read
  packages: write 

jobs:
  pipeline:
    uses: Path-Of-Execution-Team/FlashCards/.github/workflows/reusable-build-deploy.yml@main
    with:
      lang: node
      image_name: ghcr.io/path-of-execution-team/flashcardsgui
      container_name: frontend
      deployment_dev: frontend
      deployment_prod: frontend
      namespace_dev: flashcards-dev
      namespace_prod: flashcards
      build_context: .
      dockerfile: ./Dockerfile
      test_command: "npm ci && npm test --if-present"
      deploy_mode: registry
      platform: linux/arm64
    secrets: inherit
