name: ci
on:
  push: { branches: [main, dev] }
  pull_request: { branches: [main, dev] }
  workflow_dispatch:

jobs:
  pipeline:
    uses: Path-Of-Execution-Team/FlashCards/.github/workflows/reusable-build-deploy.yml@main
    with:
      lang: node
      image_name: ghcr.io/Path-Of-Execution-Team/flashcardsgui
      container_name: frontend
      deployment_dev: frontend
      deployment_prod: frontend
      namespace_dev: flashcards-dev
      namespace_prod: flashcards
      build_context: .
      dockerfile: ./Dockerfile
      test_command: "npm ci && npm test --if-present"
      deploy_mode: direct
      platform: linux/arm64
    secrets: inherit
